// src/pages/index.js
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Next.js App
        </h1>
        <p className={styles.description}>
          Get started by editing <code className={styles.code}>src/pages/index.js</code>
        </p>
      </main>
    </div>
  )
}
